services:
  esecai-cache:
    image: redis:7-alpine
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - esecai-net
    volumes:
      - redis_data:/data

  # esecai-api:
  #   build:
  #     dockerfile: Dockerfile
  #   container_name: esecai-api
  #   depends_on:
  #     - esecai-db
  #   networks:
  #     - esecai-net
  #   env_file:
  #   - ./.env

  esecai-db:
    image: postgres:17-alpine
    container_name: esecai-db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - esecai-net
    env_file:
    - ./.env

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    networks:
      - esecai-net
    env_file:
    - ./.env

networks:
  esecai-net:
    driver: bridge

volumes:
  postgres_data:
  redis_data: