services:
  # Image for MinIO storage
  esecai-storage:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports: 
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./.env
    networks:
      - esecai-net
    volumes: 
      - minio_data:/data

  # Image for redis cache
  esecai-cache:
    image: redis:7-alpine
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - esecai-net
    volumes:
      - redis_data:/data

  # Image for backend server
  # esecai-api:
  #   build:
  #     dockerfile: Dockerfile
  #   container_name: esecai-api
  #   depends_on:
  #     - esecai-db
  #   networks:
  #     - esecai-net
  #   env_file:
  #   - ./.env

  # Image for PostgreSQL DB
  esecai-db:
    image: postgres:17-alpine
    container_name: esecai-db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - esecai-net
    env_file:
    - ./.env

  # Image cloudflare tunnel
  esecai-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    networks:
      - esecai-net
    env_file:
    - ./.env

networks:
  esecai-net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  minio_data: