// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using esecai.Infrastructure.Data;

#nullable disable

namespace esecai.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404054457_RemoveRubricMetadata")]
    partial class RemoveRubricMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("esecai.Domain.Entities.Assessment", b =>
                {
                    b.Property<Guid>("ass_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Questionquest_id")
                        .HasColumnType("uuid");

                    b.Property<string>("ass_answer_key_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ass_created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ass_instruction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ass_status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("draft");

                    b.Property<string>("ass_title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("ass_total_points")
                        .HasColumnType("real");

                    b.Property<string>("ass_type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ass_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("class_id")
                        .HasColumnType("uuid");

                    b.HasKey("ass_id");

                    b.HasIndex("Questionquest_id");

                    b.HasIndex("class_id");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("esecai.Domain.Entities.Classroom", b =>
                {
                    b.Property<Guid>("class_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("class_banner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("class_created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("class_description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("class_is_archived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("class_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("class_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("class_id");

                    b.HasIndex("class_id");

                    b.HasIndex("user_id");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("esecai.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("notif_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("notif_created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("notif_is_read")
                        .HasColumnType("boolean");

                    b.Property<string>("notif_message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("notif_title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("notif_id");

                    b.HasIndex("user_id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("esecai.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("quest_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ass_id")
                        .HasColumnType("uuid");

                    b.Property<float>("quest_ai_confidence")
                        .HasColumnType("real");

                    b.Property<string>("quest_correct_answer")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<float>("quest_max_points")
                        .HasColumnType("real");

                    b.Property<int>("quest_num")
                        .HasColumnType("integer");

                    b.Property<string>("quest_text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("quest_type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("quest_id");

                    b.HasIndex("ass_id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("esecai.Domain.Entities.Record", b =>
                {
                    b.Property<Guid>("rec_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ass_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("rec_created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("rec_graded_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("rec_percentage")
                        .HasColumnType("real");

                    b.Property<string>("rec_scan_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("rec_status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending");

                    b.Property<string>("rec_student_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("rec_total_score")
                        .HasColumnType("real");

                    b.HasKey("rec_id");

                    b.HasIndex("ass_id");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("esecai.Domain.Entities.RecordAnswer", b =>
                {
                    b.Property<Guid>("ra_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("quest_id")
                        .HasColumnType("uuid");

                    b.Property<float>("ra_ai_confidence")
                        .HasColumnType("real");

                    b.Property<float>("ra_awarded_pts")
                        .HasColumnType("real");

                    b.Property<string>("ra_feedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ra_raw_response")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ra_student_ans")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<float>("ra_teacher_op")
                        .HasColumnType("real");

                    b.Property<bool>("ra_teacher_rev")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("rec_id")
                        .HasColumnType("uuid");

                    b.HasKey("ra_id");

                    b.HasIndex("quest_id");

                    b.HasIndex("rec_id");

                    b.ToTable("RecordAnswers");
                });

            modelBuilder.Entity("esecai.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("display_image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("is_admin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("is_email_verified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("refreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("refreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("user_created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("user_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("user_id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("esecai.Domain.Entities.Assessment", b =>
                {
                    b.HasOne("esecai.Domain.Entities.Question", null)
                        .WithMany("assessments")
                        .HasForeignKey("Questionquest_id");

                    b.HasOne("esecai.Domain.Entities.Classroom", "classroom")
                        .WithMany("assessments")
                        .HasForeignKey("class_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("classroom");
                });

            modelBuilder.Entity("esecai.Domain.Entities.Classroom", b =>
                {
                    b.HasOne("esecai.Domain.Entities.User", "user")
                        .WithMany("classrooms")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("esecai.Domain.Entities.Notification", b =>
                {
                    b.HasOne("esecai.Domain.Entities.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("esecai.Domain.Entities.Question", b =>
                {
                    b.HasOne("esecai.Domain.Entities.Assessment", "assessment")
                        .WithMany("questions")
                        .HasForeignKey("ass_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("assessment");
                });

            modelBuilder.Entity("esecai.Domain.Entities.Record", b =>
                {
                    b.HasOne("esecai.Domain.Entities.Assessment", "assessment")
                        .WithMany("records")
                        .HasForeignKey("ass_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("assessment");
                });

            modelBuilder.Entity("esecai.Domain.Entities.RecordAnswer", b =>
                {
                    b.HasOne("esecai.Domain.Entities.Question", "question")
                        .WithMany("record_answers")
                        .HasForeignKey("quest_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("esecai.Domain.Entities.Record", "record")
                        .WithMany("record_answers")
                        .HasForeignKey("rec_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("question");

                    b.Navigation("record");
                });

            modelBuilder.Entity("esecai.Domain.Entities.Assessment", b =>
                {
                    b.Navigation("questions");

                    b.Navigation("records");
                });

            modelBuilder.Entity("esecai.Domain.Entities.Classroom", b =>
                {
                    b.Navigation("assessments");
                });

            modelBuilder.Entity("esecai.Domain.Entities.Question", b =>
                {
                    b.Navigation("assessments");

                    b.Navigation("record_answers");
                });

            modelBuilder.Entity("esecai.Domain.Entities.Record", b =>
                {
                    b.Navigation("record_answers");
                });

            modelBuilder.Entity("esecai.Domain.Entities.User", b =>
                {
                    b.Navigation("classrooms");
                });
#pragma warning restore 612, 618
        }
    }
}
