// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using esecai.Infrastructure.Data;

#nullable disable

namespace esecai.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304115307_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("esecai.Domain.Entities.Classroom", b =>
                {
                    b.Property<Guid>("class_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("class_created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("class_description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("class_image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("class_is_archived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("class_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("class_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("class_id");

                    b.HasIndex("class_id");

                    b.HasIndex("user_id");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("esecai.Domain.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("enroll_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("class_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("enroll_created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("enroll_is_approved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("enroll_id");

                    b.HasIndex("class_id");

                    b.HasIndex("user_id");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("esecai.Domain.Entities.Posting", b =>
                {
                    b.Property<Guid>("post_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("class_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("post_created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("post_details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("post_heading")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("post_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("post_id");

                    b.HasIndex("class_id");

                    b.ToTable("Postings");
                });

            modelBuilder.Entity("esecai.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("sub_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("post_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("sub_created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("sub_remark")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("sub_score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("sub_id");

                    b.HasIndex("post_id");

                    b.HasIndex("user_id");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("esecai.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("display_image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("is_admin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("is_email_verified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("refreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("refreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("user_created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("user_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("user_id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("esecai.Domain.Entities.Classroom", b =>
                {
                    b.HasOne("esecai.Domain.Entities.User", "user")
                        .WithMany("classrooms")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("esecai.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("esecai.Domain.Entities.Classroom", "classroom")
                        .WithMany()
                        .HasForeignKey("class_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("esecai.Domain.Entities.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("classroom");

                    b.Navigation("user");
                });

            modelBuilder.Entity("esecai.Domain.Entities.Posting", b =>
                {
                    b.HasOne("esecai.Domain.Entities.Classroom", "classroom")
                        .WithMany()
                        .HasForeignKey("class_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("classroom");
                });

            modelBuilder.Entity("esecai.Domain.Entities.Submission", b =>
                {
                    b.HasOne("esecai.Domain.Entities.Posting", "posting")
                        .WithMany()
                        .HasForeignKey("post_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("esecai.Domain.Entities.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("posting");

                    b.Navigation("user");
                });

            modelBuilder.Entity("esecai.Domain.Entities.User", b =>
                {
                    b.Navigation("classrooms");
                });
#pragma warning restore 612, 618
        }
    }
}
